name: ğŸ› Update dependencies
# On Wednesdays, we update our dependencies.

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * 3

jobs:
  update:
    name: ğŸ¦¿ Update dependencies
    uses: quaternionmedia/.github/.github/workflows/update.yml@main
